version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: messaging_app
    build: .
    ports:
      - "8000:8000"

volumes:
  db_data:
